name: Check Storage and RAM

on: workflow_dispatch

jobs:
  check-resources:
    runs-on: ubuntu-22.04

    steps:
      - name: Check Initial RAM and Storage
        run: |
          free -h
          df -h

      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          swap-size-mb: 24576

      - name: Check Storage After Cleanup
        run: |
          free -h
          df -h