name: Build V

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      KEY_PASS: ${{ secrets.KEY_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disk Cleanup & Status
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 6

      - name: Setup, Get Tags, Tools, Clone & RBE Auth
        run: |
          git config --global user.name "bimuafaq"
          git config --global user.email "133272416+bimuafaq@users.noreply.github.com"
          sudo apt-get update -qq && sudo apt-get install -y -qq default-jdk jq curl
          
          LATEST_TAG=$(curl -sL https://api.github.com/repos/GrapheneOS/Vanadium/releases/latest | jq -r .tag_name)
          CHROMIUM_VERSION=${LATEST_TAG%.*}
          
          echo "VANADIUM_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "CHROMIUM_VERSION=$CHROMIUM_VERSION" >> $GITHUB_ENV
          
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
          
          git clone --depth=1 --branch $LATEST_TAG https://github.com/GrapheneOS/Vanadium.git
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > Vanadium/vanadium.keystore
          
          cat << EOF > $GITHUB_WORKSPACE/siso-credential-helper.sh
          #!/bin/bash
          cat << JSON
          {
            "headers": { "x-buildbuddy-api-key": ["$BUILDBUDDY_API_KEY"] },
            "expires": "\$(date --date='now +6 hours' -Iseconds)"
          }
          JSON
          EOF
          chmod +x $GITHUB_WORKSPACE/siso-credential-helper.sh
          echo "SISO_CREDENTIAL_HELPER=$GITHUB_WORKSPACE/siso-credential-helper.sh" >> $GITHUB_ENV

      - name: Configure, Sync, Patch & Runhooks
        run: |
          cd Vanadium
          
          cat <<EOF > .gclient
          solutions = [
            {
              "name": "src",
              "url": "https://chromium.googlesource.com/chromium/src.git",
              "managed": False,
              "custom_vars": {
                "rbe_instance": "default_instance",
                "reapi_address": "nano.buildbuddy.io:443",
                "reapi_backend_config_path": "${GITHUB_WORKSPACE}/Vanadium/src/buildbuddy_backend.star"
              },
            },
          ]
          target_os = ["android"]
          EOF

          gclient sync --nohooks --no-history --with_tags --revision src@${{ env.CHROMIUM_VERSION }}
          
          cat <<EOF > src/buildbuddy_backend.star
          load("@builtin//struct.star", "module")

          def __platform_properties(ctx):
              container_image = "docker://gcr.io/chops-public-images-prod/rbe/siso-chromium/linux@sha256:d7cb1ab14a0f20aa669c23f22c15a9dead761dcac19f43985bf9dd5f41fbef3a"
              return {
                  "default": {
                      "OSFamily": "Linux",
                      "container-image": container_image,
                  },
                  "large": {
                      "OSFamily": "Linux",
                      "container-image": container_image,
                  },
              }

          backend = module(
              "backend",
              platform_properties = __platform_properties,
          )
          EOF

          sudo DEBIAN_FRONTEND=noninteractive src/build/install-build-deps.sh --android --no-prompt &> /dev/null
          
          cd src
          git am --whitespace=nowarn --keep-non-patch ../patches/*.patch
          cd ..
          
          gclient runhooks

      - name: GN
        run: |
          cd Vanadium
          CERT_DIGEST=$(keytool -export-cert -alias vanadium -keystore vanadium.keystore -storepass "$KEY_PASS" | sha256sum | awk '{print $1}')
          cd src
          mkdir -p out/Default
          cp ../args.gn out/Default/args.gn
          sed -i "s/trichrome_certdigest = .*/trichrome_certdigest = \"$CERT_DIGEST\"/" out/Default/args.gn
          sed -i "s/config_apk_certdigest = .*/config_apk_certdigest = \"$CERT_DIGEST\"/" out/Default/args.gn
          sed -i "s/symbol_level = 1/symbol_level = 0/" out/Default/args.gn
          cat <<EOF >> out/Default/args.gn
          use_remoteexec = true
          v8_symbol_level = 0
          blink_symbol_level = 0
          EOF
          
          gn gen out/Default

      - name: Build
        run: |
          export RBE_exec_strategy=remote_local_fallback
          export RBE_num_remote_reruns=1
          cd Vanadium/src          
          siso ninja -k 0 -C out/Default chrome_public_apk

      - name: Sign & Pack
        run: |
          cd Vanadium
          echo "$KEY_PASS" | ./generate-release src/out/Default
          tar -czf ../vanadium_build.tar.gz src/out/Default/apks

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VANADIUM_TAG }}
          files: vanadium_build.tar.gz
          prerelease: true